[package]
name = "auth-service"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.8.6"
axum-extra = { version = "0.12.1", features = ["cookie"] }
tokio = { version = "1.48.0", features = ["full"] }
tower-http = { version = "0.6.6", features = ["fs", "cors", "trace"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
uuid = { version = "1.18.1", features = ["v4", "serde"] }
async-trait = "0.1.89"
validator = "=0.20.0"
jsonwebtoken = { version = "10.2.0", features = ["rust_crypto"] }
chrono = "0.4.42"
dotenvy = "0.15.7"
lazy_static = "1.4.0"
rand = "0.9.2"
sqlx = { version = "0.8.6", features = [ "runtime-tokio-rustls", "postgres", "migrate"] }
argon2 = { version = "0.5.3", features = ["std"] }
redis = { version = "0.32.7", features = ["tokio-comp"] }
test_helpers = { git = "https://github.com/letsgetrusty/test-helpers.git" }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = ["registry", "env-filter"] }
tracing-error = "0.2.1"
thiserror = "2.0.17"
color-eyre = "0.6.5"
secrecy = { version = "0.10.3", features = ["serde"] }
reqwest = { version = "0.12.24", default-features = false, features = ["json", "rustls-tls", "cookies"] }

[dev-dependencies]
fake = "=4.4.0"
quickcheck = "1.0.3"
quickcheck_macros = "1.1.0"
wiremock = "0.6.5"